services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.8
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.7.8
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  kafka-init:
    image: confluentinc/cp-kafka:7.7.8
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 20
        kafka-topics --create --if-not-exists --topic traffic-data --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
        kafka-topics --create --if-not-exists --topic critical-traffic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
        echo "Kafka topics are ready."

  producer:
    image: python:3.11-slim
    container_name: producer
    depends_on:
      - kafka-init
    working_dir: /opt/project
    command: >
      bash -c "pip install --no-cache-dir kafka-python==2.0.2 && tail -f /dev/null"
    volumes:
      - ./:/opt/project

  spark-master:
    image: apache/spark:3.5.1-python3
    container_name: spark-master
    hostname: spark-master
    environment:
      HOME: /tmp
    command:
      - /bin/bash
      - -c
      - mkdir -p /tmp/.ivy2 && /opt/spark/sbin/start-master.sh && tail -f /dev/null
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./:/opt/project

  spark-worker:
    image: apache/spark:3.5.1-python3
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      HOME: /tmp
    command:
      - /bin/bash
      - -c
      - mkdir -p /tmp/.ivy2 && /opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null
    ports:
      - "8081:8081"
    volumes:
      - ./:/opt/project

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: airflow-init
    user: "50000:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      "
    volumes:
      - airflow_home:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./reports:/opt/airflow/reports

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    user: "50000:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    command: airflow webserver
    ports:
      - "8088:8080"
    volumes:
      - airflow_home:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./reports:/opt/airflow/reports

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    user: "50000:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    command: airflow scheduler
    volumes:
      - airflow_home:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./reports:/opt/airflow/reports

volumes:
  airflow_home:
